=== loganDTR/event-driven-architecture-lab/contracts/fraud-checked.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "FraudChecked",
  "description": "Evento emesso dopo la valutazione antifrode di un ordine.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "eventId",
    "eventType",
    "eventVersion",
    "occurredAt",
    "producer",
    "correlationId",
    "causationId",
    "aggregateId",
    "payload"
  ],
  "properties": {
    "eventId": {
      "$ref": "./common/definitions.schema.json#/$defs/eventId"
    },
    "eventType": {
      "const": "fraud.checked"
    },
    "eventVersion": {
      "const": 1
    },
    "occurredAt": {
      "$ref": "./common/definitions.schema.json#/$defs/timestamp"
    },
    "producer": {
      "$ref": "./common/definitions.schema.json#/$defs/serviceName"
    },
    "correlationId": {
      "$ref": "./common/definitions.schema.json#/$defs/correlationId"
    },
    "causationId": {
      "$ref": "./common/definitions.schema.json#/$defs/causationId"
    },
    "aggregateId": {
      "$ref": "./common/definitions.schema.json#/$defs/aggregateId"
    },
    "payload": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "checkId",
        "orderId",
        "decision",
        "riskScore",
        "checkedAt",
        "reasons"
      ],
      "properties": {
        "checkId": {
          "type": "string",
          "minLength": 1
        },
        "orderId": {
          "type": "string",
          "minLength": 1
        },
        "decision": {
          "type": "string",
          "enum": [
            "APPROVED",
            "REJECTED",
            "REVIEW"
          ]
        },
        "riskScore": {
          "type": "number",
          "minimum": 0,
          "maximum": 100
        },
        "checkedAt": {
          "$ref": "./common/definitions.schema.json#/$defs/timestamp"
        },
        "reasons": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          },
          "uniqueItems": true
        }
      }
    }
  }
}

=== loganDTR/event-driven-architecture-lab/contracts/examples/fraud-checked.valid.json
{
  "eventId": "5bc5d969-cc7f-43f5-bf0e-44aec65587cf",
  "eventType": "fraud.checked",
  "eventVersion": 1,
  "occurredAt": "2026-07-22T08:00:08Z",
  "producer": "fraud-service",
  "correlationId": "2c29018f-d449-46d7-915a-1e91b892804e",
  "causationId": "4b107bab-d9b3-4dfa-971f-768991a02f97",
  "aggregateId": "ORD-10001",
  "payload": {
    "checkId": "CHK-70001",
    "orderId": "ORD-10001",
    "decision": "APPROVED",
    "riskScore": 18.5,
    "checkedAt": "2026-07-22T08:00:08Z",
    "reasons": [
      "KNOWN_CUSTOMER",
      "LOW_ORDER_VALUE"
    ]
  }
}
